name: ${name}
description: ${description}
version: ${version}
main: dev.xhyrom.lighteco.currency.money.paper.PaperMCLoader
author: ${author}
api-version: 1.17
load: STARTUP

softdepend:
  - Vault
  - LightEco
